name: Continuous Integration Workflow

permissions:
  actions: write

on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches:
      - main

jobs:
  cache_trimmer:
    uses: ./.github/workflows/cache_prunner.yaml

  flutter_analyzer:
    uses: ./.github/workflows/dart_analyzer.yaml
